from ollama import chat
from pydantic import BaseModel
import json

planner_prompt = f"""You are a planner agent whose goal is to draft three tags and a short summary.
        Given a title and content, your task is to do these steps:
        1. Generate three relevant tags and a one-sentence summary of the content. The three tags should describe the content, an example being e.g. ['vector clocks', 'partial ordering', 'conflict resolution'].
        2. Write a one-sentence summary with a strict less than 25 word limit.
        3.Return only valid JSON, with information on tags and summary."""

 
reviewer_prompt = f"""You are a reviewer agent whose goal is to review the tags and summary generated by the planner agent.
        Given the title and content, as well as the generated tags and summary from the planner agent, your task is to do these steps:
            1. Take in title, content, tags, and summary as input.
            2. Review the tags and summary for accuracy and relevance.
            3. Check if the summary is less than 25 words and if the tags are relevant to the content.
            4. Check if the tags are unique and not repetitive.
            5. Provide feedback on the tags and summary, suggesting improvements if necessary.
            6. Return only valid JSON, with information on tags, summary, changed, and explanation.
    )"""

# Step 1: Load the local model via Ollama

# Planner
def create_planner(title, content):
    response = chat(
        model="qwen3:8b",
        messages=[{"role": "system", "content": planner_prompt}, {"role": "user", "content": f"""Title: {title}, Content: {content}"""}],
        format="json"
    )
    return response.message.content

# Reviewer
def create_reviewer(title, content, tags, summary):
    response = chat(
        model="qwen3:8b",
        messages=[{"role": "system", "content": reviewer_prompt}, {"role": "user", "content": f"""Title: {title}, Content: {content}, Tags: {tags}, Summary: {summary}"""}],
        format="json"
    )
    return response.message.content

# Finalization step
def finalize(title, content):
    planner_response = create_planner(title, content)
    print("Planner output")
    print(planner_response)
    planner_data = json.loads(planner_response)  # Convert string to dictionary
    tags = planner_data.get("tags", [])
    summary = planner_data.get("summary", "")

    print("Reviewer output")
    print(reviewer_response)
    reviewer_response = create_reviewer(title, content, tags, summary)
    reviewer_data = json.loads(reviewer_response)  # Convert string to dictionary

    final = json.dumps({"tags": reviewer_data["tags"], "summary": reviewer_data["summary"]})
    print(final)  # Print the final output as a JSON string
    return final
