from ollama import chat
from pydantic import BaseModel

planner_prompt = f"""Run a planner agent
        name="Planner",
        role="You are a planner agent whose goal is to draft three tags and a short summary.",
        goals=[
            "The plan is to take in title and content as input.",
            "The plan is to draft three tags, an example being e.g. ['vector clocks', 'partial ordering', 'conflict resolution']",
            "The plan is to write a one-sentence summary with a strict less than 25 word limit.",
            "Return only valid JSON."
        ],
    )"""
 
# Step 1: Load the local model via Ollama

# Planner
def create_planner(title, content):
    response = chat(
        model="qwen3:8b",
        messages=[{"role": "system", "content": planner_prompt}, {"role": "user", "content": f"""Title: {title}, Content: {content}"""}],
        format="json"
    )
    return response.message.content

reviewer_prompt = f"""Run a reviewer agent
        name="Reviewer",
        role="You are a reviewer agent whose goal is to review the tags and summary generated by the planner agent.",
        goals=[
            "The plan is to take in title, content, tags, and summary as input.",
            "The plan is to review the tags and summary for accuracy and relevance.",
            "The plan is to check if the summary is less than 25 words and if the tags are relevant to the content.",
            "The plan is to check if the tags are unique and not repetitive.",
            "The plan is to provide feedback on the tags and summary, suggesting improvements if necessary.",
            "Return only valid JSON."
        ],
    )"""

# Reviewer
def create_reviewer(title, content, tags, summary):
    response = chat(
        model="qwen3:8b",
        messages=[{"role": "system", "content": reviewer_prompt}, {"role": "user", "content": f"""Title: {title}, Content: {content}, Tags: {tags}, Summary: {summary}"""}],
        format="json"
    )
    return response.message.content

# Finalization step